
// If the tag is not in rules dictionary the tag will be filled with random characters 
// 
// If the tag's value in rules dict == "" the data_element will not be changed.
// If the tag's value in rules dict is other than "" the rule value will 
// overwrite the data_element's value character-by-character, except where
// the rule is "?". Where the rule is "?" the original character will be 
// kept in the data_element value.


var RULES_DICT = {
    "FileMetaInformationGroupLength": "",
    "MediaStorageSOPClassUID": "",
    "MediaStorageSOPInstanceUID": "",
    "TransferSyntaxUID": "",
    "SpecificCharacterSet": "",
    "ImageType": "",
    "InstanceCreationDate": "18001212",
    "InstanceCreationTime": "18001212",
    "SOPClassUID": "",
    "SOPInstanceUID": "",
    "StudyDate": "18001212",
    "SeriesDate": "18001212",
    "AcquisitionDate": "18001212",
    "ContentDate": "18001212",
    "StudyTime": "111111",
    "SeriesTime": "111111",
    "AcquisitionTime": "111111",
    "ContentTime": "111111",
    "AccessionNumber": "1",
    "Modality": "",
    "Manufacturer": "",
    "InstitutionName": "test",
    "InstitutionAddress": "test",
    "ReferringPhysicianName": "test",
    "StationName": "test",
    "StudyDescription": "",
    "SeriesDescription": "",
    "InstitutionalDepartmentName": "test",
    "PerformingPhysicianName": "test",
    "NameOfPhysiciansReadingStudy": "test",
    "ManufacturerModelName": "",
    "ReferencedImageSequence": "",
    "ReferencedSOPClassUID": "",
    "ReferencedSOPInstanceUID": "",
    "ReferencedSOPClassUID": "",
    "ReferencedSOPInstanceUID": "",
    "ReferencedSOPClassUID": "",
    "ReferencedSOPInstanceUID": "",
    "PatientName": "test^test",
    "PatientID": "1",
    "PatientBirthDate": "18001212",
    "PatientSex": "",
    "PatientAge": "",
    "PatientSize": "",
    "PatientWeight": "",
    "BodyPartExamined": "",
    "ScanningSequence": "",
    "SequenceVariant": "",
    "ScanOptions": "",
    "MRAcquisitionType": "",
    "SequenceName": "",
    "AngioFlag": "",
    "SliceThickness": "",
    "RepetitionTime": "",
    "EchoTime": "",
    "NumberOfAverages": "",
    "ImagingFrequency": "",
    "ImagedNucleus": "",
    "EchoNumbers": "",
    "MagneticFieldStrength": "",
    "SpacingBetweenSlices": "",
    "NumberOfPhaseEncodingSteps": "",
    "EchoTrainLength": "",
    "PercentSampling": "",
    "PercentPhaseFieldOfView": "",
    "PixelBandwidth": "",
    "DeviceSerialNumber": "tets",
    "SoftwareVersions": "",
    "ProtocolName": "",
    "TransmitCoilName": "",
    "AcquisitionMatrix": "",
    "InPlanePhaseEncodingDirection": "",
    "FlipAngle": "",
    "VariableFlipAngleFlag": "",
    "SAR": "",
    "dBdt": "",
    "PatientPosition": "",
    "StudyInstanceUID": "",
    "SeriesInstanceUID": "",
    "StudyID": "1",
    "SeriesNumber": "",
    "AcquisitionNumber": "",
    "InstanceNumber": "",
    "ImagePositionPatient": "",
    "ImageOrientationPatient": "",
    "FrameOfReferenceUID": "",
    "Laterality": "",
    "PositionReferenceIndicator": "",
    "SliceLocation": "",
    "ImageComments": "N/A",
    "SamplesPerPixel": "",
    "PhotometricInterpretation": "",
    "Rows": "",
    "Columns": "",
    "PixelSpacing": "",
    "BitsAllocated": "",
    "BitsStored": "",
    "HighBit": "",
    "PixelRepresentation": "",
    "SmallestImagePixelValue": "",
    "LargestImagePixelValue": "",
    "WindowCenter": "",
    "WindowWidth": "",
    "WindowCenterWidthExplanation": "",
    "RequestedProcedureDescription": " ",
    "StudyComments": " ",
    "PerformedProcedureStepStartDate": "18000101",
    "PerformedProcedureStepStartTime": "000000",
    "PerformedProcedureStepID": "",
    "RequestAttributesSequence": "",
    "ScheduledProcedureStepID": "",
    "CommentsOnThePerformedProcedureStep": " ",
    "PixelData": "",
    "PersonName": "N/A",
    "VerifyingObserverName": "N/A",
    "InterpretationTranscriber": "N/A",
    "InterpretationAuthor": "N/A",
};